### ISSUE TITLE
Copyright date

### ISSUE THREAD

**Issue by leicray** [openvar/VVweb#54]
The copyright date statement for web pages is set statically in line 165 of `VVweb/web/templates/base.html` which is used as a skeleton for other web pages. Consequently, the copyright year does not update automatically and it currently shows as 2019.

The date could be auto updated by changing line 165 to read:

`<p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> VariantValidator Contributors</p>`

To take full account of the exact time of day at which the new year actually begins, change line 165 to read:

`<p>Copyright &copy; <script>document.write(new Date().getUTCFullYear() );</script> VariantValidator Contributors</p>`

**Comment by PeteCausey-Freeman** [comment]
Discussed not practical but we have implemented a simple find and replace
